#ifndef LEXER_LETTERS_H
#define LEXER_LETTERS_H

#include <cstdint>

namespace Lexer {
	enum class LexicalChar : char32_t {
		NULL_CHAR = 0x00,
		LINE_FEED = 0x0A,
		CARRIGE_RETURN = 0x0D,
		LINE_SEPERATOR = 0x2028,
		PARAGRAPH_SEPERATOR = 0x2029,
		UPPERCASE_A = 0X41,
		UPPERCASE_B = 0X42,
		UPPERCASE_C = 0X43,
		UPPERCASE_D = 0X44,
		UPPERCASE_E = 0X45,
		UPPERCASE_F = 0X46,
		UPPERCASE_G = 0X47,
		UPPERCASE_H = 0X48,
		UPPERCASE_I = 0X49,
		UPPERCASE_J = 0X4A,
		UPPERCASE_K = 0X4B,
		UPPERCASE_L = 0X4C,
		UPPERCASE_M = 0X4D,
		UPPERCASE_N = 0X4E,
		UPPERCASE_O = 0X4F,
		UPPERCASE_P = 0X50,
		UPPERCASE_Q = 0X51,
		UPPERCASE_R = 0X52,
		UPPERCASE_S = 0X53,
		UPPERCASE_T = 0X54,
		UPPERCASE_U = 0X55,
		UPPERCASE_V = 0X56,
		UPPERCASE_W = 0X57,
		UPPERCASE_X = 0x58,
		UPPERCASE_Y = 0x59,
		UPPERCASE_Z = 0x5A,
		LOWERCASE_A = 0x61,
		LOWERCASE_B = 0x62,
		LOWERCASE_C = 0x63,
		LOWERCASE_D = 0x64,
		LOWERCASE_E = 0X65,
		LOWERCASE_F = 0X66,
		LOWERCASE_G = 0X67,
		LOWERCASE_H = 0X68,
		LOWERCASE_I = 0X69,
		LOWERCASE_J = 0X6A,
		LOWERCASE_K = 0X6B,
		LOWERCASE_L = 0X6C,
		LOWERCASE_M = 0X6D,
		LOWERCASE_N = 0X6E,
		LOWERCASE_O = 0X6F,
		LOWERCASE_P = 0x70,
		LOWERCASE_Q = 0x71,
		LOWERCASE_R = 0x72,
		LOWERCASE_S = 0x73,
		LOWERCASE_T = 0x74,
		LOWERCASE_U = 0x75,
		LOWERCASE_V = 0x76,
		LOWERCASE_W = 0x77,
		LOWERCASE_X = 0x78,
		LOWERCASE_Y = 0x79,
		LOWERCASE_Z = 0x7A,
		BACKSPACE = 0x08,        /* backspace */
		TAB = 0x09,
		VT = 0x0B,        /* liner tabulation */
		FORM_FEED = 0x0C,       
		SPACE = 0x20,   
		NB_SPACE = 0xA0,      /* no-break space */
		ZWNBSP = 0xFEFF,  /* zero width no-break space */
		MVS = 0x180e,     /* MONGOLIAN VOWEL SEPARATOR (U+180E) */
		NEXT_LINE = 0x85,
		OGHAM = 0x1680,
		ENQUAD = 0X2000,
		ZERO_WIDTH_SP = 0x200B,
		NARROW_NO_BREAK_SP = 0x202F,
		MATHEMATICAL_SP = 0x205F,
		IDEOGRAPHIC_SP = 0x3000,
		DOUBLE_QUOTE = 0x22, 
		DOLLAR_SIGN = 0x24, 
		SINGLE_QUOTE = 0x27, 
		NUM_0 = 0x30,
		NUM_1 = 0x31,
		NUM_2 = 0x32,
		NUM_3 = 0x33,
		NUM_4 = 0x34,
		NUM_5 = 0x35,
		NUM_6 = 0x36,
		NUM_7 = 0x37,
		NUM_8 = 0x38,
		NUM_9 = 0x39,
		BACKSLASH = 0X5c,  /* \ */
		UNDERSCORE = 0x5F, /* _ */
		EXCLAMATION = 0x21,  /* exclamation mark */
		PERCENT = 0x25,      /* percent sign */
		AMPERSAND = 0x26,    /* ampersand */
		LEFT_PAREN = 0x28,   /* left parenthesis */
		RIGHT_PAREN = 0x29,  /* right parenthesis */
		ASTERISK = 0x2A,     /* asterisk */
		PLUS = 0x2B,         /* plus sign */
		COMMA = 0x2C,        /* comma */
		MINUS = 0x2D,        /* hyphen-minus */
		DOT = 0x2E,          /* dot */
		SLASH = 0x2F,        /* solidus */
		COLON = 0x3A,        /* colon */
		SEMICOLON = 0x3B,    /* semicolon */
		LESS_THAN = 0x3C,    /* less-than sign */
		EQUALS = 0x3D,       /* equals sign */
		GREATER_THAN = 0x3E, /* greater-than sign */
		QUESTION = 0x3F,     /* question mark */
		LEFT_SQUARE = 0x5B,  /* left square bracket */
		RIGHT_SQUARE = 0x5D, /* right square bracket */
		CIRCUMFLEX = 0x5E,   /* circumflex accent */
		LEFT_CURLY_BRACE = 0x7B,   /* left curly bracket */
		VLINE = 0x7C,        /* vertical line */
		RIGHT_CURLY_BRACE = 0x7D,  /* right curly bracket */
		TILDE = 0x7E,        /* tilde */
		BACK_TICK = 0x60,    /* back tick */
		HASH_MARK = 0x23,    /* hash mark */
		AT = 0x40,           /* at */
		ZWNJ = 0x200C, /* zero width non-joiner */
		ZWJ = 0x200D,  /* zero width joiner */
		VERTICAL_TILDE = 0x2E2F, /* vertical tilde */
		UTF8_2_BYTE_CODE_POINT_MIN = 0x80,
		UTF8_EXTRA_BYTE_MASK = 0xC0,
		CHAR_EOS = 0xFFFF,
		UNICODE_CODE_POINT_MAX = 0x10FFFF,
		UNICODE_INVALID_CP = UINT32_MAX
	};
}

#endif
